### ISSUE TITLE
How to create vertical scrollbar without pagination and fixed header

### ISSUE THREAD

**Issue by BattiniSantthosh** [ssuperczynski/ngx-easy-table#252]
Can you please help to create vertical scrollbar without pagination and fixed header, if it is possible please share the sample URL?

**Comment by ssuperczynski** [comment]
You need to play with table styles:

```css
:host /deep/ thead tr:nth-child(1) th {
  background: white;
  position: sticky;
  top: 0;
  z-index: 10;
}

:host /deep/ table {
    height: 200px;
    overflow: auto;
    display: block;
}
```

However this is not tested. In version 11 I plan to add CDK scroll.
