### ISSUE TITLE
delete placeholder

### ISSUE THREAD

**Issue by mnovoa** [ssuperczynski/ngx-easy-table#94]
Hello

There is some way to eliminate the placeholder, I want to leave blank space

greetings and again congratulations for this great software

**Comment by ssuperczynski** [comment]
The easiest way to hide these placeholder texts is to add below selector to your scss file:

```css
:host /deep/ .ngx-table__header-search::-webkit-input-placeholder{
  color: transparent;
}
```
